services:
  s3admin:
    image: dpage/pgadmin4:latest
    container_name: 68-s3-admin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: s6702041511241@email.kmutnb.ac.th
      PGADMIN_DEFAULT_PASSWORD: ThanapatPgadmin1
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"

    ports:
      - "5050:80"

    volumes:
      - pgadmin-data:/var/lib/pgadmin

    networks:
      - backend

volumes:
  pgadmin-data:

networks:
  backend:
    driver: bridge
